version: '3.8'
services:
    backend-test:
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        depends_on:
            - backend-test-db
        ports:
            - '8080:8080'
        volumes:
            - ./:/app
    backend-test-db:
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: users
        volumes:
            - /app/node_modules
            - ./data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
